version: '3'

vars: 
  MIRROR: ''

tasks:
  rocky9-vmware:
    dir: rockylinux
    cmds:
    - packer  build -only=vmware-iso.rockylinux-9-aarch64 .

  alma9-vmware:
    dir: almalinux
    cmds:
    - packer  build -only=vmware-iso.almalinux-9-aarch64 . 
  ubuntu-2204:
    dir: ubuntu
    cmds:
    - packer  build -only=sources.vmware-iso.ubuntu-2204-aarch64 . 

  ubuntu-2404:
    dir: ubuntu
    cmds:
    - packer  build -only=sources.vmware-iso.ubuntu-2404-aarch64 . 
